### ISSUE TITLE
Errors caused by first time installation through git url

### ISSUE THREAD

**Issue by zcha621** [liris-xr/PLUME-Recorder#1]
I followed the instructions on importing PLUME to my new unity project.
However, I encountered the following problem(my Unity version and the error are shown in the screenshot):

![image](https://github.com/liris-xr/PLUME-Recorder/assets/17682668/6b3bf7ed-139c-475d-b9c6-45d2e28f740a)

**Comment by cjaverliat** [comment]
Hello, thank you for letting me know. The meta file for the LICENSE is a quick fix, regarding the error with NUnit, this is something I noticed before and was often fixed by restarting the Unity Editor. But I will take a deeper look so that it doesn't occur at all. I will keep you updated.

**Comment by cjaverliat** [comment]
Added the LICENSE.meta in commit 17f40fa.

**Comment by cjaverliat** [comment]
This should be fixed in v1.0.1-beta. Could you try to install the PLUME-Recorder again from the Git URL in a fresh project and tell me if any new error occurs?

Thank you :)

**Comment by zcha621** [comment]
Thanks so much for your update. 
Now the errors are fixed. Here is how I did:
1. I removed the old version in the unity package manager
2. restart unity
3. install package from Git URL
4. Done
